### ISSUE TITLE
Hi Adconsulting

### ISSUE THREAD

**Issue by tommy537** [Adconsulting/Adc.Odoo#1]
I'm try use connector, but when i load res.partner with OdooForeignKey, It's return null ?

**Comment by Adconsulting** [comment]
Hello, 

thx for the feedback, could you provide the source code and exception for your problem? so i can test tis on my system?

kind regards, 
Gelootn

**Comment by tommy537** [comment]
Thanks Adconsulting
I had take screen
![test](https://cloud.githubusercontent.com/assets/7719106/14624355/2e8ff942-0604-11e6-9b9f-fd77b9aaeafe.png)

**Comment by Adconsulting** [comment]
Hello, 

i have pushed a version 2 branch witch includes a fix for this problem. 
could you test with the new branch?

**Comment by tommy537** [comment]
It fixed, thanks Adconsulting. (y)
